// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PasswordService is an autogenerated mock type for the PasswordService type
type PasswordService struct {
	mock.Mock
}

type PasswordService_Expecter struct {
	mock *mock.Mock
}

func (_m *PasswordService) EXPECT() *PasswordService_Expecter {
	return &PasswordService_Expecter{mock: &_m.Mock}
}

// HashPassword provides a mock function with given fields: password
func (_m *PasswordService) HashPassword(password string) (string, error) {
	ret := _m.Called(password)

	if len(ret) == 0 {
		panic("no return value specified for HashPassword")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(password)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PasswordService_HashPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HashPassword'
type PasswordService_HashPassword_Call struct {
	*mock.Call
}

// HashPassword is a helper method to define mock.On call
//   - password string
func (_e *PasswordService_Expecter) HashPassword(password interface{}) *PasswordService_HashPassword_Call {
	return &PasswordService_HashPassword_Call{Call: _e.mock.On("HashPassword", password)}
}

func (_c *PasswordService_HashPassword_Call) Run(run func(password string)) *PasswordService_HashPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *PasswordService_HashPassword_Call) Return(_a0 string, _a1 error) *PasswordService_HashPassword_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PasswordService_HashPassword_Call) RunAndReturn(run func(string) (string, error)) *PasswordService_HashPassword_Call {
	_c.Call.Return(run)
	return _c
}

// NewPasswordService creates a new instance of PasswordService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPasswordService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PasswordService {
	mock := &PasswordService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
