// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	model "go-musthave-diploma-tpl/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// ClientInterface is an autogenerated mock type for the ClientInterface type
type ClientInterface struct {
	mock.Mock
}

type ClientInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *ClientInterface) EXPECT() *ClientInterface_Expecter {
	return &ClientInterface_Expecter{mock: &_m.Mock}
}

// GetOrderInfo provides a mock function with given fields: ctx, orderNumber
func (_m *ClientInterface) GetOrderInfo(ctx context.Context, orderNumber string) (*model.AccrualSystemResponse, error) {
	ret := _m.Called(ctx, orderNumber)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderInfo")
	}

	var r0 *model.AccrualSystemResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.AccrualSystemResponse, error)); ok {
		return rf(ctx, orderNumber)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.AccrualSystemResponse); ok {
		r0 = rf(ctx, orderNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AccrualSystemResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orderNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClientInterface_GetOrderInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderInfo'
type ClientInterface_GetOrderInfo_Call struct {
	*mock.Call
}

// GetOrderInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - orderNumber string
func (_e *ClientInterface_Expecter) GetOrderInfo(ctx interface{}, orderNumber interface{}) *ClientInterface_GetOrderInfo_Call {
	return &ClientInterface_GetOrderInfo_Call{Call: _e.mock.On("GetOrderInfo", ctx, orderNumber)}
}

func (_c *ClientInterface_GetOrderInfo_Call) Run(run func(ctx context.Context, orderNumber string)) *ClientInterface_GetOrderInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ClientInterface_GetOrderInfo_Call) Return(_a0 *model.AccrualSystemResponse, _a1 error) *ClientInterface_GetOrderInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClientInterface_GetOrderInfo_Call) RunAndReturn(run func(context.Context, string) (*model.AccrualSystemResponse, error)) *ClientInterface_GetOrderInfo_Call {
	_c.Call.Return(run)
	return _c
}

// NewClientInterface creates a new instance of ClientInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientInterface {
	mock := &ClientInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
