// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	model "go-musthave-diploma-tpl/internal/model"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// BalanceRepository is an autogenerated mock type for the BalanceRepository type
type BalanceRepository struct {
	mock.Mock
}

type BalanceRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *BalanceRepository) EXPECT() *BalanceRepository_Expecter {
	return &BalanceRepository_Expecter{mock: &_m.Mock}
}

// AddAccrual provides a mock function with given fields: ctx, userID, amount
func (_m *BalanceRepository) AddAccrual(ctx context.Context, userID uuid.UUID, amount float32) error {
	ret := _m.Called(ctx, userID, amount)

	if len(ret) == 0 {
		panic("no return value specified for AddAccrual")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, float32) error); ok {
		r0 = rf(ctx, userID, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BalanceRepository_AddAccrual_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddAccrual'
type BalanceRepository_AddAccrual_Call struct {
	*mock.Call
}

// AddAccrual is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - amount float32
func (_e *BalanceRepository_Expecter) AddAccrual(ctx interface{}, userID interface{}, amount interface{}) *BalanceRepository_AddAccrual_Call {
	return &BalanceRepository_AddAccrual_Call{Call: _e.mock.On("AddAccrual", ctx, userID, amount)}
}

func (_c *BalanceRepository_AddAccrual_Call) Run(run func(ctx context.Context, userID uuid.UUID, amount float32)) *BalanceRepository_AddAccrual_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(float32))
	})
	return _c
}

func (_c *BalanceRepository_AddAccrual_Call) Return(_a0 error) *BalanceRepository_AddAccrual_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BalanceRepository_AddAccrual_Call) RunAndReturn(run func(context.Context, uuid.UUID, float32) error) *BalanceRepository_AddAccrual_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, balance
func (_m *BalanceRepository) Create(ctx context.Context, balance *model.Balance) error {
	ret := _m.Called(ctx, balance)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Balance) error); ok {
		r0 = rf(ctx, balance)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BalanceRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type BalanceRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - balance *model.Balance
func (_e *BalanceRepository_Expecter) Create(ctx interface{}, balance interface{}) *BalanceRepository_Create_Call {
	return &BalanceRepository_Create_Call{Call: _e.mock.On("Create", ctx, balance)}
}

func (_c *BalanceRepository_Create_Call) Run(run func(ctx context.Context, balance *model.Balance)) *BalanceRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Balance))
	})
	return _c
}

func (_c *BalanceRepository_Create_Call) Return(_a0 error) *BalanceRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BalanceRepository_Create_Call) RunAndReturn(run func(context.Context, *model.Balance) error) *BalanceRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserID provides a mock function with given fields: ctx, userID
func (_m *BalanceRepository) GetByUserID(ctx context.Context, userID uuid.UUID) (*model.Balance, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 *model.Balance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Balance, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Balance); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Balance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BalanceRepository_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type BalanceRepository_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *BalanceRepository_Expecter) GetByUserID(ctx interface{}, userID interface{}) *BalanceRepository_GetByUserID_Call {
	return &BalanceRepository_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, userID)}
}

func (_c *BalanceRepository_GetByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *BalanceRepository_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *BalanceRepository_GetByUserID_Call) Return(_a0 *model.Balance, _a1 error) *BalanceRepository_GetByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *BalanceRepository_GetByUserID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.Balance, error)) *BalanceRepository_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, balance
func (_m *BalanceRepository) Update(ctx context.Context, balance *model.Balance) error {
	ret := _m.Called(ctx, balance)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Balance) error); ok {
		r0 = rf(ctx, balance)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BalanceRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type BalanceRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - balance *model.Balance
func (_e *BalanceRepository_Expecter) Update(ctx interface{}, balance interface{}) *BalanceRepository_Update_Call {
	return &BalanceRepository_Update_Call{Call: _e.mock.On("Update", ctx, balance)}
}

func (_c *BalanceRepository_Update_Call) Run(run func(ctx context.Context, balance *model.Balance)) *BalanceRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Balance))
	})
	return _c
}

func (_c *BalanceRepository_Update_Call) Return(_a0 error) *BalanceRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BalanceRepository_Update_Call) RunAndReturn(run func(context.Context, *model.Balance) error) *BalanceRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// WithdrawWithRecord provides a mock function with given fields: ctx, userID, orderNumber, amount
func (_m *BalanceRepository) WithdrawWithRecord(ctx context.Context, userID uuid.UUID, orderNumber string, amount float32) error {
	ret := _m.Called(ctx, userID, orderNumber, amount)

	if len(ret) == 0 {
		panic("no return value specified for WithdrawWithRecord")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, float32) error); ok {
		r0 = rf(ctx, userID, orderNumber, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BalanceRepository_WithdrawWithRecord_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithdrawWithRecord'
type BalanceRepository_WithdrawWithRecord_Call struct {
	*mock.Call
}

// WithdrawWithRecord is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - orderNumber string
//   - amount float32
func (_e *BalanceRepository_Expecter) WithdrawWithRecord(ctx interface{}, userID interface{}, orderNumber interface{}, amount interface{}) *BalanceRepository_WithdrawWithRecord_Call {
	return &BalanceRepository_WithdrawWithRecord_Call{Call: _e.mock.On("WithdrawWithRecord", ctx, userID, orderNumber, amount)}
}

func (_c *BalanceRepository_WithdrawWithRecord_Call) Run(run func(ctx context.Context, userID uuid.UUID, orderNumber string, amount float32)) *BalanceRepository_WithdrawWithRecord_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(float32))
	})
	return _c
}

func (_c *BalanceRepository_WithdrawWithRecord_Call) Return(_a0 error) *BalanceRepository_WithdrawWithRecord_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BalanceRepository_WithdrawWithRecord_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, float32) error) *BalanceRepository_WithdrawWithRecord_Call {
	_c.Call.Return(run)
	return _c
}

// NewBalanceRepository creates a new instance of BalanceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBalanceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *BalanceRepository {
	mock := &BalanceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
