// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	model "go-musthave-diploma-tpl/internal/model"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// OrderRepository is an autogenerated mock type for the OrderRepository type
type OrderRepository struct {
	mock.Mock
}

type OrderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderRepository) EXPECT() *OrderRepository_Expecter {
	return &OrderRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, order
func (_m *OrderRepository) Create(ctx context.Context, order *model.Order) error {
	ret := _m.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Order) error); ok {
		r0 = rf(ctx, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrderRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type OrderRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - order *model.Order
func (_e *OrderRepository_Expecter) Create(ctx interface{}, order interface{}) *OrderRepository_Create_Call {
	return &OrderRepository_Create_Call{Call: _e.mock.On("Create", ctx, order)}
}

func (_c *OrderRepository_Create_Call) Run(run func(ctx context.Context, order *model.Order)) *OrderRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Order))
	})
	return _c
}

func (_c *OrderRepository_Create_Call) Return(_a0 error) *OrderRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderRepository_Create_Call) RunAndReturn(run func(context.Context, *model.Order) error) *OrderRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByNumber provides a mock function with given fields: ctx, number
func (_m *OrderRepository) GetByNumber(ctx context.Context, number string) (*model.Order, error) {
	ret := _m.Called(ctx, number)

	if len(ret) == 0 {
		panic("no return value specified for GetByNumber")
	}

	var r0 *model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Order, error)); ok {
		return rf(ctx, number)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Order); ok {
		r0 = rf(ctx, number)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, number)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderRepository_GetByNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByNumber'
type OrderRepository_GetByNumber_Call struct {
	*mock.Call
}

// GetByNumber is a helper method to define mock.On call
//   - ctx context.Context
//   - number string
func (_e *OrderRepository_Expecter) GetByNumber(ctx interface{}, number interface{}) *OrderRepository_GetByNumber_Call {
	return &OrderRepository_GetByNumber_Call{Call: _e.mock.On("GetByNumber", ctx, number)}
}

func (_c *OrderRepository_GetByNumber_Call) Run(run func(ctx context.Context, number string)) *OrderRepository_GetByNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *OrderRepository_GetByNumber_Call) Return(_a0 *model.Order, _a1 error) *OrderRepository_GetByNumber_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderRepository_GetByNumber_Call) RunAndReturn(run func(context.Context, string) (*model.Order, error)) *OrderRepository_GetByNumber_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserID provides a mock function with given fields: ctx, userID
func (_m *OrderRepository) GetByUserID(ctx context.Context, userID uuid.UUID) ([]*model.Order, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 []*model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*model.Order, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*model.Order); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderRepository_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type OrderRepository_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *OrderRepository_Expecter) GetByUserID(ctx interface{}, userID interface{}) *OrderRepository_GetByUserID_Call {
	return &OrderRepository_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, userID)}
}

func (_c *OrderRepository_GetByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *OrderRepository_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *OrderRepository_GetByUserID_Call) Return(_a0 []*model.Order, _a1 error) *OrderRepository_GetByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderRepository_GetByUserID_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*model.Order, error)) *OrderRepository_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrdersByStatus provides a mock function with given fields: ctx, statuses
func (_m *OrderRepository) GetOrdersByStatus(ctx context.Context, statuses []model.OrderStatus) ([]*model.Order, error) {
	ret := _m.Called(ctx, statuses)

	if len(ret) == 0 {
		panic("no return value specified for GetOrdersByStatus")
	}

	var r0 []*model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []model.OrderStatus) ([]*model.Order, error)); ok {
		return rf(ctx, statuses)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []model.OrderStatus) []*model.Order); ok {
		r0 = rf(ctx, statuses)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []model.OrderStatus) error); ok {
		r1 = rf(ctx, statuses)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderRepository_GetOrdersByStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrdersByStatus'
type OrderRepository_GetOrdersByStatus_Call struct {
	*mock.Call
}

// GetOrdersByStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - statuses []model.OrderStatus
func (_e *OrderRepository_Expecter) GetOrdersByStatus(ctx interface{}, statuses interface{}) *OrderRepository_GetOrdersByStatus_Call {
	return &OrderRepository_GetOrdersByStatus_Call{Call: _e.mock.On("GetOrdersByStatus", ctx, statuses)}
}

func (_c *OrderRepository_GetOrdersByStatus_Call) Run(run func(ctx context.Context, statuses []model.OrderStatus)) *OrderRepository_GetOrdersByStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]model.OrderStatus))
	})
	return _c
}

func (_c *OrderRepository_GetOrdersByStatus_Call) Return(_a0 []*model.Order, _a1 error) *OrderRepository_GetOrdersByStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderRepository_GetOrdersByStatus_Call) RunAndReturn(run func(context.Context, []model.OrderStatus) ([]*model.Order, error)) *OrderRepository_GetOrdersByStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, orderID, status, accrual
func (_m *OrderRepository) UpdateStatus(ctx context.Context, orderID uuid.UUID, status model.OrderStatus, accrual float32) error {
	ret := _m.Called(ctx, orderID, status, accrual)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.OrderStatus, float32) error); ok {
		r0 = rf(ctx, orderID, status, accrual)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrderRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type OrderRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
//   - status model.OrderStatus
//   - accrual float32
func (_e *OrderRepository_Expecter) UpdateStatus(ctx interface{}, orderID interface{}, status interface{}, accrual interface{}) *OrderRepository_UpdateStatus_Call {
	return &OrderRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, orderID, status, accrual)}
}

func (_c *OrderRepository_UpdateStatus_Call) Run(run func(ctx context.Context, orderID uuid.UUID, status model.OrderStatus, accrual float32)) *OrderRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.OrderStatus), args[3].(float32))
	})
	return _c
}

func (_c *OrderRepository_UpdateStatus_Call) Return(_a0 error) *OrderRepository_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderRepository_UpdateStatus_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.OrderStatus, float32) error) *OrderRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderRepository creates a new instance of OrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderRepository {
	mock := &OrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
