// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	model "go-musthave-diploma-tpl/internal/model"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// WithdrawalRepository is an autogenerated mock type for the WithdrawalRepository type
type WithdrawalRepository struct {
	mock.Mock
}

type WithdrawalRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *WithdrawalRepository) EXPECT() *WithdrawalRepository_Expecter {
	return &WithdrawalRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, withdrawal
func (_m *WithdrawalRepository) Create(ctx context.Context, withdrawal *model.Withdrawal) error {
	ret := _m.Called(ctx, withdrawal)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Withdrawal) error); ok {
		r0 = rf(ctx, withdrawal)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WithdrawalRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type WithdrawalRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - withdrawal *model.Withdrawal
func (_e *WithdrawalRepository_Expecter) Create(ctx interface{}, withdrawal interface{}) *WithdrawalRepository_Create_Call {
	return &WithdrawalRepository_Create_Call{Call: _e.mock.On("Create", ctx, withdrawal)}
}

func (_c *WithdrawalRepository_Create_Call) Run(run func(ctx context.Context, withdrawal *model.Withdrawal)) *WithdrawalRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Withdrawal))
	})
	return _c
}

func (_c *WithdrawalRepository_Create_Call) Return(_a0 error) *WithdrawalRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *WithdrawalRepository_Create_Call) RunAndReturn(run func(context.Context, *model.Withdrawal) error) *WithdrawalRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsByOrderNumber provides a mock function with given fields: ctx, orderNumber
func (_m *WithdrawalRepository) ExistsByOrderNumber(ctx context.Context, orderNumber string) (bool, error) {
	ret := _m.Called(ctx, orderNumber)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByOrderNumber")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, orderNumber)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, orderNumber)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orderNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WithdrawalRepository_ExistsByOrderNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByOrderNumber'
type WithdrawalRepository_ExistsByOrderNumber_Call struct {
	*mock.Call
}

// ExistsByOrderNumber is a helper method to define mock.On call
//   - ctx context.Context
//   - orderNumber string
func (_e *WithdrawalRepository_Expecter) ExistsByOrderNumber(ctx interface{}, orderNumber interface{}) *WithdrawalRepository_ExistsByOrderNumber_Call {
	return &WithdrawalRepository_ExistsByOrderNumber_Call{Call: _e.mock.On("ExistsByOrderNumber", ctx, orderNumber)}
}

func (_c *WithdrawalRepository_ExistsByOrderNumber_Call) Run(run func(ctx context.Context, orderNumber string)) *WithdrawalRepository_ExistsByOrderNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *WithdrawalRepository_ExistsByOrderNumber_Call) Return(_a0 bool, _a1 error) *WithdrawalRepository_ExistsByOrderNumber_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *WithdrawalRepository_ExistsByOrderNumber_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *WithdrawalRepository_ExistsByOrderNumber_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserID provides a mock function with given fields: ctx, userID
func (_m *WithdrawalRepository) GetByUserID(ctx context.Context, userID uuid.UUID) ([]*model.Withdrawal, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 []*model.Withdrawal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*model.Withdrawal, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*model.Withdrawal); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Withdrawal)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WithdrawalRepository_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type WithdrawalRepository_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *WithdrawalRepository_Expecter) GetByUserID(ctx interface{}, userID interface{}) *WithdrawalRepository_GetByUserID_Call {
	return &WithdrawalRepository_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, userID)}
}

func (_c *WithdrawalRepository_GetByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *WithdrawalRepository_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *WithdrawalRepository_GetByUserID_Call) Return(_a0 []*model.Withdrawal, _a1 error) *WithdrawalRepository_GetByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *WithdrawalRepository_GetByUserID_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*model.Withdrawal, error)) *WithdrawalRepository_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// NewWithdrawalRepository creates a new instance of WithdrawalRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWithdrawalRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *WithdrawalRepository {
	mock := &WithdrawalRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
