// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// JWTService is an autogenerated mock type for the JWTService type
type JWTService struct {
	mock.Mock
}

type JWTService_Expecter struct {
	mock *mock.Mock
}

func (_m *JWTService) EXPECT() *JWTService_Expecter {
	return &JWTService_Expecter{mock: &_m.Mock}
}

// GenerateToken provides a mock function with given fields: userID, login
func (_m *JWTService) GenerateToken(userID uuid.UUID, login string) (string, error) {
	ret := _m.Called(userID, login)

	if len(ret) == 0 {
		panic("no return value specified for GenerateToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, string) (string, error)); ok {
		return rf(userID, login)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, string) string); ok {
		r0 = rf(userID, login)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, string) error); ok {
		r1 = rf(userID, login)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// JWTService_GenerateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateToken'
type JWTService_GenerateToken_Call struct {
	*mock.Call
}

// GenerateToken is a helper method to define mock.On call
//   - userID uuid.UUID
//   - login string
func (_e *JWTService_Expecter) GenerateToken(userID interface{}, login interface{}) *JWTService_GenerateToken_Call {
	return &JWTService_GenerateToken_Call{Call: _e.mock.On("GenerateToken", userID, login)}
}

func (_c *JWTService_GenerateToken_Call) Run(run func(userID uuid.UUID, login string)) *JWTService_GenerateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(string))
	})
	return _c
}

func (_c *JWTService_GenerateToken_Call) Return(_a0 string, _a1 error) *JWTService_GenerateToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *JWTService_GenerateToken_Call) RunAndReturn(run func(uuid.UUID, string) (string, error)) *JWTService_GenerateToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewJWTService creates a new instance of JWTService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJWTService(t interface {
	mock.TestingT
	Cleanup(func())
}) *JWTService {
	mock := &JWTService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
