// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PasswordService is an autogenerated mock type for the PasswordService type
type PasswordService struct {
	mock.Mock
}

type PasswordService_Expecter struct {
	mock *mock.Mock
}

func (_m *PasswordService) EXPECT() *PasswordService_Expecter {
	return &PasswordService_Expecter{mock: &_m.Mock}
}

// CheckPassword provides a mock function with given fields: password, hash
func (_m *PasswordService) CheckPassword(password string, hash string) error {
	ret := _m.Called(password, hash)

	if len(ret) == 0 {
		panic("no return value specified for CheckPassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(password, hash)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PasswordService_CheckPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckPassword'
type PasswordService_CheckPassword_Call struct {
	*mock.Call
}

// CheckPassword is a helper method to define mock.On call
//   - password string
//   - hash string
func (_e *PasswordService_Expecter) CheckPassword(password interface{}, hash interface{}) *PasswordService_CheckPassword_Call {
	return &PasswordService_CheckPassword_Call{Call: _e.mock.On("CheckPassword", password, hash)}
}

func (_c *PasswordService_CheckPassword_Call) Run(run func(password string, hash string)) *PasswordService_CheckPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *PasswordService_CheckPassword_Call) Return(_a0 error) *PasswordService_CheckPassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PasswordService_CheckPassword_Call) RunAndReturn(run func(string, string) error) *PasswordService_CheckPassword_Call {
	_c.Call.Return(run)
	return _c
}

// NewPasswordService creates a new instance of PasswordService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPasswordService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PasswordService {
	mock := &PasswordService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
