// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// BalanceRepository is an autogenerated mock type for the BalanceRepository type
type BalanceRepository struct {
	mock.Mock
}

type BalanceRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *BalanceRepository) EXPECT() *BalanceRepository_Expecter {
	return &BalanceRepository_Expecter{mock: &_m.Mock}
}

// WithdrawWithRecord provides a mock function with given fields: ctx, userID, orderNumber, amount
func (_m *BalanceRepository) WithdrawWithRecord(ctx context.Context, userID uuid.UUID, orderNumber string, amount float32) error {
	ret := _m.Called(ctx, userID, orderNumber, amount)

	if len(ret) == 0 {
		panic("no return value specified for WithdrawWithRecord")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, float32) error); ok {
		r0 = rf(ctx, userID, orderNumber, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BalanceRepository_WithdrawWithRecord_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithdrawWithRecord'
type BalanceRepository_WithdrawWithRecord_Call struct {
	*mock.Call
}

// WithdrawWithRecord is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - orderNumber string
//   - amount float32
func (_e *BalanceRepository_Expecter) WithdrawWithRecord(ctx interface{}, userID interface{}, orderNumber interface{}, amount interface{}) *BalanceRepository_WithdrawWithRecord_Call {
	return &BalanceRepository_WithdrawWithRecord_Call{Call: _e.mock.On("WithdrawWithRecord", ctx, userID, orderNumber, amount)}
}

func (_c *BalanceRepository_WithdrawWithRecord_Call) Run(run func(ctx context.Context, userID uuid.UUID, orderNumber string, amount float32)) *BalanceRepository_WithdrawWithRecord_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(float32))
	})
	return _c
}

func (_c *BalanceRepository_WithdrawWithRecord_Call) Return(_a0 error) *BalanceRepository_WithdrawWithRecord_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BalanceRepository_WithdrawWithRecord_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, float32) error) *BalanceRepository_WithdrawWithRecord_Call {
	_c.Call.Return(run)
	return _c
}

// NewBalanceRepository creates a new instance of BalanceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBalanceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *BalanceRepository {
	mock := &BalanceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
