// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "go-musthave-diploma-tpl/internal/model"

	uuid "github.com/google/uuid"
)

// WithdrawalRepository is an autogenerated mock type for the WithdrawalRepository type
type WithdrawalRepository struct {
	mock.Mock
}

type WithdrawalRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *WithdrawalRepository) EXPECT() *WithdrawalRepository_Expecter {
	return &WithdrawalRepository_Expecter{mock: &_m.Mock}
}

// GetByUserID provides a mock function with given fields: ctx, userID
func (_m *WithdrawalRepository) GetByUserID(ctx context.Context, userID uuid.UUID) ([]model.Withdrawal, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 []model.Withdrawal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]model.Withdrawal, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []model.Withdrawal); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Withdrawal)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WithdrawalRepository_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type WithdrawalRepository_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *WithdrawalRepository_Expecter) GetByUserID(ctx interface{}, userID interface{}) *WithdrawalRepository_GetByUserID_Call {
	return &WithdrawalRepository_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, userID)}
}

func (_c *WithdrawalRepository_GetByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *WithdrawalRepository_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *WithdrawalRepository_GetByUserID_Call) Return(_a0 []model.Withdrawal, _a1 error) *WithdrawalRepository_GetByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *WithdrawalRepository_GetByUserID_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]model.Withdrawal, error)) *WithdrawalRepository_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// NewWithdrawalRepository creates a new instance of WithdrawalRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWithdrawalRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *WithdrawalRepository {
	mock := &WithdrawalRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
